services:
  app:
    build: ./.docker/node
    entrypoint: ./.docker/node/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysql',
          '--protocol=TCP',
          '-h',
          '127.0.0.1',
          '-u${MYSQL_USER}',
          '-p${MYSQL_PASSWORD}',
          '${MYSQL_DATABASE}',
          '-e',
          'SELECT 1',
        ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
