@host = http://localhost:3000

### Check API health
GET {{host}}/healthy

# Patients

### List patients
GET {{host}}/patients?page=1&limit=2

### Show patient
GET {{host}}/patients/39d16f88-537e-4aec-b8f4-7e488ad3405d

### Delete patient personal data (LGPD)
DELETE {{host}}/patients/33b418d5-1521-4640-b9d9-81ac04a0513b

### Create patient
POST {{host}}/patients
Content-Type: application/json

{
  "name": "Maria da Cunha",
  "phone": "+5516994215196",
  "email": "maria@example.com",
  "birthDate": "1995-03-02",
  "sex": "FEMALE",
  "heightM": 1.68,
  "weightKg": 65.4
}

### Update patient
PATCH {{host}}/patients/39d16f88-537e-4aec-b8f4-7e488ad3405d
Content-Type: application/json

{
  "weightKg": 95.4
}

# Appointments

### List appointments (indicates when a patient is anonymized)
GET {{host}}/appointments
    ?patientId=39d16f88-537e-4aec-b8f4-7e488ad3405d
    &from=2026-08-09T05:00:00-03:00
    &to=2026-08-09T21:00:00-03:00
    &page=1
    &limit=2

### Show appointment
GET {{host}}/appointments/0a4b9567-941e-11f1-a943-e274d4327676
